#!/usr/bin/env node

new trap ({
    name: "Trap",
    filter: function (sender={}, action='default', prop={}) {
        return true;
        return sender.meta.exchange == 'deribit';
    },
    step: function () {

    },
    watch: {
        getChartForTradingview: function () {
            this.____ = 1;
        }
    }
});