#!/usr/bin/env node

$include("delta").then(Event => {
    Event.delta();
});

new trap ({
    name: "Trap",
    filter: function (sender={}, action='default', prop={}) {
        // return true;
        return sender.meta.exchange == 'bitmex';
    },
    step: function () {
        // console.log(23)
    },
    watch: {
        getChartForTradingview: function () {
            this.____ = 1;
        },
        getPositions: function (Event) {
            console.log(__global__.delta)
        }
    }
});