#!/usr/bin/env node

new trap ({
    name: "Trap",
    filter: function (sender={}, action='default', prop={}) {
        return true;
        return sender.meta.exchange == 'deribit';
    },
    step: function () {
        // console.log(23)
    },
    watch: {
        getChartForTradingview: function () {
            this.____ = 1;
        }
    }
});

// $deribit.createLimitSellOrder('BTC-PERPETUAL', 10, 11000).then(Event => {
//     console.log(Event)
// }).catch(Event => {
//     console.log(Event)
// })