#!/usr/bin/env node
'use strict';

const async = require("async");
const prototype = require('../models/essence');

module.exports = class extends prototype {

    constructor() {

        super();

        this.meta = {
            id: 'itbe-101',
            name: "Indicators Transport by Event+",
            version: 1
        };
        this.mask = {
            'bdbe-101': {},
            'ddbe-101': {},
            'bmxdbe-101': {}
        }

    }

    calculate (e, driver, processor) {

        async.waterfall([

            // Calculate default arrays
            function (callback) {

                var object = {
                    volume: [],
                    close: [],
                    high: [],
                    low: [],
                    open: [],
                    time: []
                };

                for (const _ of e) {
                    object.volume.push(_.volume);
                    object.close.push(_.close);
                    object.high.push(_.high);
                    object.low.push(_.low);
                    object.open.push(_.open);
                    object.time.push(_.time);
                }

                callback (null, object);

            },

            // SMA
            function(chart, callback) {

                var chartData = [];
                const indicator = processor.SMA(chart.close);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key],
                        ])
                    }
                }

                callback(null, chart, chartData);

            },

            // RVI
            function (chart, SMA, callback) {

                var chartData = [];
                const indicator = processor.RVI(chart.close, chart.open, chart.high, chart.low);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key],
                        ])
                    }
                }

                callback(null, chart, SMA, chartData);

            },

            // Bollinger Bands
            function (chart, SMA, RVI, callback) {

                var chartData = [];
                const indicator = processor.BB(chart.close);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key].upper,
                            indicator[key].middle,
                            indicator[key].lower
                        ]);
                    }
                }

                callback(null, chart, SMA, RVI, chartData);

            },

            // MACD
            function (chart, SMA, RVI, BB, callback) {

                var chartData = [];

                const indicator = processor.MACD(chart.close);

                for (const key in indicator.outMACD) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.outMACD.length ) ],
                            indicator.outMACD[key],
                            indicator.outMACDSignal[key],
                            indicator.outMACDHist[key]
                        ]);
                    }
                }

                callback(null, chart, SMA, RVI, BB, chartData);

            },

            // MVRVZScope
            function (chart, SMA, RVI, BB, MACD, callback) {

                processor.MVRVZScope(chart.close).then(function (indicator) {

                    var chartData = [];

                    for (const key in indicator) {
                        chartData.push({
                            value: indicator[key],
                            time: chart.time[parseInt(key) + (chart.time.length - indicator.length)]
                        })
                    }

                    callback(null, chart, SMA, RVI, BB, MACD, chartData.sweepChart());

                });


            },

            // WMA
            function (chart, SMA, RVI, BB, MACD, MVRVZScope, callback) {

                var chartData = [];
                const indicator = processor.WMA(chart.close);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key],
                        ])
                    }
                }

                callback(null, chart, SMA, RVI, BB, MACD, MVRVZScope, chartData);

            },

            // EMA
            function (chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, callback) {

                var chartData = [];

                const indicator = processor.EMA(chart.close);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key],
                        ])
                    }
                }

                callback(null, chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, chartData);

            },

            // OBV
            function (chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, callback) {

                var chartData = [];
                const indicator = processor.OBV(chart.close, chart.volume);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key],
                        ])
                    }
                }

                callback(null, chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, chartData);

            },

            // STOCHASTIC
            function (chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, OBV, callback) {

                var chartData = [];
                const indicator = processor.STOCHASTIC(chart.close, chart.high, chart.low);

                for (const key in indicator) {
                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[ parseInt(key) + ( chart.time.length - indicator.length ) ],
                            indicator[key].k,
                            indicator[key].d
                        ]);
                    }
                }

                callback(null, chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, OBV, chartData);

            },

            // TradingVUE
            function (chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, OBV, STOCHASTIC, callback) {

                var chartData = [];

                for (const key in chart.time) {

                    if (typeof chart.time[key] == "number") {
                        chartData.push([
                            chart.time[key],
                            chart.open[key],
                            chart.high[key],
                            chart.low[key],
                            chart.close[key],
                            chart.volume[key]
                        ]);
                    }

                }

                callback(null, chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, OBV, STOCHASTIC, chartData);

            }

        ], (err, chart, SMA, RVI, BB, MACD, MVRVZScope, WMA, EMA, OBV, STOCHASTIC, TRADINGVUE) => {

            this.call('TRADINGVUE', {
                exchange: driver.meta.exchange,
                chart: TRADINGVUE
            });

            this.call('SMA', {
                exchange: driver.meta.exchange,
                chart: SMA
            });

            this.call('WMA', {
                exchange: driver.meta.exchange,
                chart: WMA
            });

            this.call('EMA', {
                exchange: driver.meta.exchange,
                chart: EMA
            });

            this.call('RVI', {
                exchange: driver.meta.exchange,
                chart: RVI
            });

            this.call('BOLL', {
                exchange: driver.meta.exchange,
                chart: BB
            });

            this.call('MACD', {
                exchange: driver.meta.exchange,
                chart: MACD
            });

            this.call('MVRVZSCOPE', {
                exchange: driver.meta.exchange,
                chart: MVRVZScope
            });

            this.call('OBV', {
                exchange: driver.meta.exchange,
                chart: OBV
            });

            this.call('STOCHASTIC', {
                exchange: driver.meta.exchange,
                chart: STOCHASTIC
            });

        });


    }

    init () {

        let processor = this.go('processor', 'indicators');
        let driver = this.go('driver');
        let logger = this.go('logger', 'logger');

        if (processor) {

            if (driver) {

                for (const [name, object] of Object.entries(driver)) {
                    if ('on' in object) {

                        object.on('getChartForTradingview', (event) => {
                            this.calculate(event, object, processor);
                        });

                        logger.log({
                            sender: `TRANSPORT / INDICATORS`,
                            message: 'Successfully subscribe on get chart event on driver for ' + name,
                            level: 'info'
                        });

                    } else {

                        logger.log({
                            sender: `TRANSPORT / INDICATORS`,
                            message: `The ${name} driver is outdated or damaged because it doesn't have the \`on\` method.`,
                            level: 'error'
                        });

                    }
                }

            } else {
                throw "Drivers is not setup";
            }

        } else {
            throw "Processor is not selected";
        }


    }

}
