#!/usr/bin/env node

var prototype = require('../models/essence');

module.exports = class extends prototype {

    constructor() {

        super();
        this.meta = {
            name: 'Bitmex Driver by Event+',
            id: 'bmxdbe-101',
            version: 1,
            exchange: 'bitmex',
            type: 'exchange'
        }

    }

    init () {

        if ('store' in this.essence) {

            if ('keystore' in this.essence['store']) {

                if ('exchange' in this.essence['store']) {

                    if ('cache' in this.essence['store']) {

                        if ('commutator' in this.essence) {

                            if ('request' in this.essence['commutator']) {

                                let BitMEXClient = require('bitmex-realtime-api');
                                let keystore = this.essence['store']['keystore'];
                                let exchange = this.essence['store']['exchange'];
                                let request = this.essence['commutator']['request'];

                                var buffer = [];
                                var chartData = [];

                                request(`https://www.bitmex.com/api/v1/trade/bucketed?binSize=1m&partial=true&count=${exchange.exchange.count}&symbol=XBTUSD&reverse=true`, (error, response, body) => {

                                    if (response && response.statusCode == 200) {

                                        const data = JSON.parse(body).reverse();
                                        buffer = data;

                                    }

                                });


                                let client = new BitMEXClient({
                                    testnet: keystore.testnet,
                                    maxTableLen: 10000
                                });

                                client.addStream('XBTUSD', 'orderBookL2_25', (data, symbol, tableName) => {

                                    let bufferOrders = {asks: [], bids: []};

                                    for (const iterator of data) {

                                        if (iterator.side == 'Buy') {
                                            bufferOrders.asks.push([
                                                parseFloat(iterator.price),
                                                parseFloat(iterator.size),
                                            ]);
                                        } else {
                                            bufferOrders.bids.push([
                                                parseFloat(iterator.price),
                                                parseFloat(iterator.size),
                                            ]);
                                        }
                                    }

                                    this.call('getOrderBook', {
                                        asks: bufferOrders.asks,
                                        bids: bufferOrders.bids
                                    });

                                });

                                // client.on('initialize', () => {
                                //     console.log(client.streams);  // Log .public, .private and .all stream names
                                // });

                                client.on('error', (event) => {
                                    this.call('error', event);
                                });

                                client.on('open', (event) => {
                                    this.call('open', event);
                                });

                                client.on('close', (event) => {
                                    this.call('close', event);
                                });

                                client.addStream('XBTUSD', 'instrument', (data, symbol, tableName) => {
                                    if (!data.length) return;

                                    const answer = data[0];

                                    this.call('getInstrument', {
                                        maxPrice24h: answer.highPrice,
                                        minPrice24h: answer.lowPrice,
                                        changePrice24h: answer.lastChangePcnt,
                                        totalTurnover: answer.totalTurnover,
                                        totalTurnover24h: answer.turnover24h,
                                        volume24h: answer.volume24h,
                                        openInterest: answer.openInterest,
                                        openValue: answer.openValue,
                                        fundingRate: answer.fundingRate,
                                        lastPrice: answer.lastPrice
                                    });

                                });

                                client.addStream('XBTUSD', 'tradeBin1m', (data, symbol, tableName) => {

                                    if (!data.length) return;

                                    if (Symbol.iterator in Object(data)) {

                                        for (const iterator of data) {
                                            buffer.append(iterator, exchange.exchange.limit)
                                        }

                                    } else {
                                        buffer.append(data, exchange.exchange.limit);
                                    }

                                    for(var i = 0; i < buffer.length; i++) {

                                        if (buffer[i] === undefined) continue;
                                        var bufferData = buffer[i];

                                        chartData.append({
                                            time: Date.parse(bufferData.timestamp) / 1000,
                                            open: bufferData.open,
                                            low: bufferData.low,
                                            high: bufferData.high,
                                            close: bufferData.close,
                                            volume: bufferData.volume,
                                        }, exchange.exchange.limit);

                                    }


                                    this.call('getChartForTradingview', chartData);

                                });

                                // client.addStream('XBTUSD', 'chat', (data, symbol, tableName) => {
                                //
                                //     if (!data.length) return;
                                //
                                //     console.log(data)
                                //
                                // });

                                this.call('init', true);

                            } else {
                                throw 'No request commutator found for driver';
                            }

                        } else {
                            throw 'No commutator found for driver';
                        }

                    } else {
                        throw 'No exchange object found for driver';
                    }

                } else {
                    throw 'No cache storage found for driver caches';
                }

            } else {
                throw 'No key storage found for driver';
            }

        } else {
            throw 'No storage found for driver';
        }

    }

}
