#!/usr/bin/env node

/**
 * Express is a minimalistic and flexible web framework for Node.js applications,
 * providing an extensive feature set for mobile and web applications.
 *
 * @type {createError}
 */


var prototype = require('../models/essence');

module.exports = class extends prototype {

    constructor() {

        super();

        this.meta = {
            id: 'grbe-101',
            name: "Getaway RestAPI by Event+",
            version: 1
        };

    }

    init () {

        const express                   = this.essence['router']['express'];
        const passport                  = this.essence['router']['passport'];
        const connection                = this.essence['commutator']['mysql'];
        const authenticationMiddleware  = this.essence['router']['authenticationMiddleware'];

        var indexRouter = require('../routes')(passport, authenticationMiddleware)
        var studioRouter = require('../routes/studio')(passport, authenticationMiddleware)
        var usersRouter = require('../routes/users')(passport, authenticationMiddleware)
        var signupRouter = require('../routes/signup')(passport, authenticationMiddleware);
        var loginRouter = require('../routes/login')(passport, authenticationMiddleware);
        var logoutRouter = require('../routes/logout')(passport, authenticationMiddleware);
        var rest = require('../routes/rest')(passport, authenticationMiddleware, connection);

        express.use('/', indexRouter);
        express.use('/studio', studioRouter);
        express.use('/user', usersRouter);
        express.use('/signup', signupRouter);
        express.use('/login', loginRouter);
        express.use('/logout', logoutRouter);
        express.use('/api', rest);

        this.call('init', true);

    }

}