#!/usr/bin/env node

const Feed = require('rss-to-json');
const cache = require("cache");
const c = new cache(15 * 60 * 1000);

module.exports = class {

    constructor() {

    }

    load (url='https://www.coindesk.com/feed') {
        return Feed.load(url);
    }

    on (action='default', callback=null) {
        return this.actions.push({
            action: action,
            function: callback
        });
    }

    call (action='default', data) {
        for (const callback of this.actions) {
            if (action === callback.action) {
                try {
                    callback.function(data)
                } catch (e) {
                    console.error(e)
                }
            }
        }
    }

    init () {
        this.call('init', true);
    }

    get () {
        if (c.get('provider-feed')) {

            return new Promise((resolve, reject) => {
                resolve(c.get('provider-feed'));
            });

        } else {

            return new Promise((resolve, reject) => {
                this.load().then(function (e) {
                    c.put('provider-feed', e);
                    resolve(e);
                });
            });

        }
    }

}