#!/usr/bin/env node

var signupBuilder = require('../builder/signup');

module.exports = connection => {

    return function (req, username, password, done) {

        var signup = new signupBuilder();

        signup.use('mysql', connection)

        signup.set('username', username);
        signup.set('password', password);
        signup.set('name', req.body.name);

        signup.build();

        signup.run().then(event => {

            return done(null, {
                id: event.user.id,
                username: username,
                scope: event.user.scope,
                name: req.body.name
            });

        }).catch(event => {

            return done(false, false, event);

        });

    }

};